name: fixer_system
description: A new Flutter project.
version: 1.4.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterflow_ui_pro:
    git:
      url: https://github.com/joeshwoa/flutterflow_ui_pro
      ref: main   # Optional: specify the branch, commit, or tag if needed
  adaptive_theme: ^3.6.0
  shared_preferences: ^2.3.3
  badges: ^3.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  conditional_builder_null_safety: ^0.0.6
  bot_toast: ^4.1.3
  icons_launcher: ^3.0.0
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.8
  pager: ^0.0.6
  searchfield: ^1.1.7
  pdf: ^3.11.1
  path_provider: ^2.1.5
  printing: ^5.13.4
  faker: ^2.2.0
  flutter_lints: ^5.0.0
  image: ^4.3.0
  lints: ^5.0.0
  auto_size_text: ^3.0.0
  google_fonts: any
  flutter_animate: any
  pdfrx: ^1.0.88

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/Hacen_Tunisia/

icons_launcher:
  image_path: "assets/images/51.png"
  platforms:
    windows:
      enable: true
      image_path: "assets/images/51.png"
